# Generated by Django 4.2 on 2024-09-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Код'),
        ),
    ]
