# Generated by Django 4.2 on 2024-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uC5kG1sdOOBYx2Ll3P4so1$Fe2D1EbRRQbeSqQ/DEI+aKwRNvV78YOmOmqyT4V17bE=', max_length=128, verbose_name='password'),
        ),
    ]
