# Generated by Django 4.2 on 2024-09-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$JV304i1ZgqXOyMjJrm3SjT$kpC03AwCV7V404UM0C8BvNR6Am7xNae6CujBArRiLLs=', max_length=128, verbose_name='password'),
        ),
    ]
