# Generated by Django 4.2 on 2024-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$JqmLeVwYL99KuMkGENHmuh$EqV4yHw0UubfN3Li8VnnorP4qAhPt1o84VeRYBlOZFU=', max_length=128, verbose_name='password'),
        ),
    ]
