# Generated by Django 4.2 on 2024-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Qg270HLOJSaJrxLikk6tCj$ZDSW8W4FC8HKhlYUpK+HM39E6WbWcdM46tt3HIZzvfM=', max_length=128, verbose_name='password'),
        ),
    ]
